# Generated by Django 5.2.17 on 2026-09-24 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title (French)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title (English)')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description_fr', models.TextField(blank=True, verbose_name='description (French)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title (French)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title (English)')),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('clear_text_explanation_fr', models.TextField(blank=True, verbose_name='explanation (French, Markdown)')),
                ('clear_text_explanation_en', models.TextField(blank=True, verbose_name='explanation (English, Markdown)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('mastered', 'Mastered')], default='draft', max_length=10)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curriculum.chapter')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_fr', models.TextField(blank=True, verbose_name='question (French)')),
                ('question_text_en', models.TextField(blank=True, verbose_name='question (English)')),
                ('explanation_fr', models.TextField(blank=True, verbose_name='explanation (French)')),
                ('explanation_en', models.TextField(blank=True, verbose_name='explanation (English)')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='curriculum.concept')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book_section', 'Book section'), ('youtube_reference', 'YouTube reference'), ('falstad_simulation', 'Falstad simulation')], max_length=20)),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title (French)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title (English)')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='curriculum.concept')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('youtube_obs_embedded_url', models.URLField(blank=True, max_length=500)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='curriculum.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user progress',
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_concept_slug_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'concept'), name='unique_progress_per_user_concept'),
        ),
    ]
