# Generated by Django 5.2.17 on 2026-09-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_fr', models.CharField(blank=True, max_length=300, verbose_name='answer (French)')),
                ('text_en', models.CharField(blank=True, max_length=300, verbose_name='answer (English)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='curriculum.flashcard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
