# Generated by Django 5.2.17 on 2026-09-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'id'], 'verbose_name': 'chapter', 'verbose_name_plural': 'chapters'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'answer choice', 'verbose_name_plural': 'answer choices'},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['order', 'id'], 'verbose_name': 'concept', 'verbose_name_plural': 'concepts'},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['id'], 'verbose_name': 'quiz question', 'verbose_name_plural': 'quiz questions'},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'progress entry', 'verbose_name_plural': 'progress entries'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_fr',
            field=models.CharField(max_length=200, verbose_name='title (French)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='curriculum.flashcard', verbose_name='quiz question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_fr',
            field=models.CharField(max_length=300, verbose_name='answer (French)'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curriculum.chapter', verbose_name='chapter'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('mastered', 'Mastered')], default='draft', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='title_fr',
            field=models.CharField(max_length=200, verbose_name='title (French)'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='curriculum.concept', verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question_text_fr',
            field=models.TextField(verbose_name='question (French)'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='curriculum.concept', verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='type',
            field=models.CharField(choices=[('book_section', 'Book section'), ('youtube_reference', 'YouTube reference'), ('falstad_simulation', 'Falstad simulation')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='curriculum.concept', verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='youtube_obs_embedded_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='my video (YouTube URL)'),
        ),
    ]
